<?php

namespace Container1aiKBjL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AoZ4V9YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aoZ4V9Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aoZ4V9Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'criteria' => ['privates', '.errored..service_locator.aoZ4V9Y.Doctrine\\Common\\Collections\\Criteria', NULL, 'Cannot autowire service ".service_locator.aoZ4V9Y": it references class "Doctrine\\Common\\Collections\\Criteria" but no such service exists.'],
        ], [
            'criteria' => 'Doctrine\\Common\\Collections\\Criteria',
        ]);
    }
}
