<?php

namespace Container1aiKBjL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCriteriaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aoZ4V9Y.Doctrine\Common\Collections\Criteria' shared service.
     *
     * @return \Doctrine\Common\Collections\Criteria
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.aoZ4V9Y": it references class "Doctrine\\Common\\Collections\\Criteria" but no such service exists.');
    }
}
