<?php

namespace Container1aiKBjL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOlaMundoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OlaMundoController' shared autowired service.
     *
     * @return \App\Controller\OlaMundoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/OlaMundoController.php';

        return $container->services['App\\Controller\\OlaMundoController'] = new \App\Controller\OlaMundoController();
    }
}
