<?php

namespace ContainerRWT8K5T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedicoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MedicoController' shared autowired service.
     *
     * @return \App\Controller\MedicoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/MedicoController.php';

        return $container->services['App\\Controller\\MedicoController'] = new \App\Controller\MedicoController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
