<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHlGgp1b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHlGgp1b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHlGgp1b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHlGgp1b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHlGgp1b\App_KernelDevDebugContainer([
    'container.build_hash' => 'HlGgp1b',
    'container.build_id' => 'b907112e',
    'container.build_time' => 1626480209,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHlGgp1b');
