<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJczQSON\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJczQSON/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJczQSON.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJczQSON\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJczQSON\App_KernelDevDebugContainer([
    'container.build_hash' => 'JczQSON',
    'container.build_id' => '5ab22dcc',
    'container.build_time' => 1626138448,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJczQSON');
