<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_medico_novomedico' => [[], ['_controller' => 'App\\Controller\\MedicoController::novoMedico'], [], [['text', '/medicos']], [], []],
    'app_medico_buscarmedicos' => [[], ['_controller' => 'App\\Controller\\MedicoController::buscarMedicos'], [], [['text', '/medicos']], [], []],
    'app_medico_medicoporid' => [['id'], ['_controller' => 'App\\Controller\\MedicoController::medicoPorId'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/medicos']], [], []],
    'app_medico_atualizarmedico' => [['id'], ['_controller' => 'App\\Controller\\MedicoController::atualizarMedico'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/medicos']], [], []],
    'app_medico_removermedico' => [['id'], ['_controller' => 'App\\Controller\\MedicoController::removerMedico'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/medicos']], [], []],
    'app_olamundo_olamundo' => [[], ['_controller' => 'App\\Controller\\OlaMundoController::olaMundoAction'], [], [['text', '/ola']], [], []],
    'app_olamundo_hello' => [[], ['_controller' => 'App\\Controller\\OlaMundoController::helloAction'], [], [['text', '/hello']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
