<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_medico_novo' => [[], ['_controller' => 'App\\Controller\\MedicoController::novo'], [], [['text', '/medico']], [], []],
    'app_olamundo_olamundo' => [[], ['_controller' => 'App\\Controller\\OlaMundoController::olaMundoAction'], [], [['text', '/ola']], [], []],
    'app_olamundo_hello' => [[], ['_controller' => 'App\\Controller\\OlaMundoController::helloAction'], [], [['text', '/hello']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
