<?php

namespace ContainerJu87obY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4tMAjVpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4tMAjVp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4tMAjVp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medico' => ['privates', '.errored..service_locator.4tMAjVp.App\\Entity\\Medico', NULL, 'Cannot autowire service ".service_locator.4tMAjVp": it references class "App\\Entity\\Medico" but no such service exists.'],
        ], [
            'medico' => 'App\\Entity\\Medico',
        ]);
    }
}
