<?php

namespace ContainerHlGgp1b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedicoFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Helper\MedicoFactory' shared autowired service.
     *
     * @return \App\Helper\MedicoFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Helper/MedicoFactory.php';

        return $container->services['App\\Helper\\MedicoFactory'] = new \App\Helper\MedicoFactory();
    }
}
